version: '3.1'

services:
    db:
        image: redislabs/redisgraph
        ports:
            - "6379:6379"
    app:
        build: .
        ports:
            - "5000:5000"

        expose:
            - "5000"